# -*- coding: utf-8 -*-
"""download.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3xJq1fIh5_A7FYRoETVrECL_eipECMv
"""

import requests
from datetime import datetime, timedelta
import pandas as pd
import time
import random
from dotenv import dotenv_values

# Load environment variables from .env file
env_vars = dotenv_values()
buffer_full_path = env_vars['FILE_BUFFER_PATH']

def scrape_from_traffy():
    datetimeToday = datetime.today()
    date = datetimeToday

    result = []

    while True:
        date_string = date.strftime("%Y-%m-%d")

        # Generate a random delay between 0.5 and 1.5 seconds
        # delay = random.uniform(0.5, 1.5)
        # time.sleep(delay)

        res = requests.get(f"https://publicapi.traffy.in.th/share/teamchadchart/geojson?start={date_string}&end={date_string}")
        for i in res.json()['features']:
            result.append(i['geometry']|i['properties'])

        print(date_string, len(res.json()['features']), len(result))

        # Stop when get data for one month
        if date != datetimeToday and date.strftime("%d") == datetimeToday.strftime("%d"):
            break
        date = date - timedelta(days=1)

    df = pd.DataFrame(result)
    print(df.shape)

    df.to_csv(buffer_full_path+"raw_data.csv",index=False)